apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: logging-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: navabnaeem/usersdetails:fe-v5 
          env:
            - name: BACKEND_URL
              value: http://service-b:8000
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: logging-test
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000
  selector:
    app: service-a

